version: "3.8"
services:
    oc-dashboard-voila:
        container_name: oc-dashboard-voila
        build:
            context: ./
            dockerfile: Dockerfile
        restart: always
        volumes:
          - ./script:/app/script
        command: voila --Voila.ip=0.0.0.0 --port=8866 script/TestVoila.ipynb --no-browser
        ports:
          - "8866:8866"
        networks:
            - dashboard-voila-network
            
networks:
    dashboard-voila-network:
        driver: bridge